services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard solo accesible localmente
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.traefik.rule=Host(`localhost`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.strip-dashboard.stripPrefix.prefixes=/dashboard"
      - "traefik.http.routers.traefik.middlewares=strip-dashboard"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$dhfKKzDd$$1llfwmUPc7hQ3tbx3ypEw/"

  registro-app:
    build:
      context: ./registro-app
    labels:
      - "traefik.http.routers.registro.rule=Host(`localhost`) && PathPrefix(`/registro`)"
      - "traefik.http.routers.registro.entrypoints=web"
      - "traefik.http.routers.registro.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$dhfKKzDd$$1llfwmUPc7hQ3tbx3ypEw/"
      - "traefik.http.services.registro.loadbalancer.server.port=5000"

  cliente-app1:
    build:
      context: ./cliente-app
    environment:
      - SERVICE_ID=app1
    labels:
      - "traefik.http.routers.app1.rule=Host(`localhost`) && PathPrefix(`/cliente/app1`)"
      - "traefik.http.middlewares.strip-app1.stripPrefix.prefixes=/cliente/app1"
      - "traefik.http.routers.app1.middlewares=strip-app1"
      - "traefik.http.services.app1.loadbalancer.server.port=5000"

  cliente-app2:
    build:
      context: ./cliente-app
    environment:
      - SERVICE_ID=app2
    labels:
      - "traefik.http.routers.app2.rule=Host(`localhost`) && PathPrefix(`/cliente/app2`)"
      - "traefik.http.middlewares.strip-app2.stripPrefix.prefixes=/cliente/app2"
      - "traefik.http.routers.app2.middlewares=strip-app2"
      - "traefik.http.services.app2.loadbalancer.server.port=5000"

  cliente-app3:
    build:
      context: ./cliente-app
    environment:
      - SERVICE_ID=app3
    labels:
      - "traefik.http.routers.app3.rule=Host(`localhost`) && PathPrefix(`/cliente/app3`)"
      - "traefik.http.middlewares.strip-app3.stripPrefix.prefixes=/cliente/app3"
      - "traefik.http.routers.app3.middlewares=strip-app3"
      - "traefik.http.services.app3.loadbalancer.server.port=5000"

  monitor:
    build:
      context: ./monitor
    labels:
      - "traefik.http.routers.monitor.rule=Host(`localhost`) && PathPrefix(`/monitor`)"
      - "traefik.http.routers.monitor.entrypoints=web"
      - "traefik.http.middlewares.strip-monitor.stripPrefix.prefixes=/monitor"
      - "traefik.http.routers.monitor.middlewares=strip-monitor"
      - "traefik.http.services.monitor.loadbalancer.server.port=80"

  looger-central:
    build:
      context: ./logger-central
    labels:
      - "traefik.http.routers.logger.rule=Host(`localhost`) && PathPrefix(`/logger`)"
      - "traefik.http.routers.logger.entrypoints=web"
      - "traefik.http.middlewares.strip-logger.stripPrefix.prefixes=/logger"
      - "traefik.http.routers.logger.middlewares=strip-logger"
      - "traefik.http.services.logger.loadbalancer.server.port=80"


  
